# implicit rules

CC_NAME  = CC
CXX_NAME = C++
LD_NAME  = LD

CC_BANNER =	@if [ -t 1 ]; then \
			echo "\t\033[0;1;33m$(CC_NAME)\033[0m   $(DIR)$<"; \
		else \
			echo "\t$(CC_NAME)   $(DIR)$<"; \
		fi

CXX_BANNER =	@if [ -t 1 ]; then \
			echo "\t\033[0;1;33m$(CXX_NAME)\033[0m  $(DIR)$<"; \
		else \
			echo "\t$(CXX_NAME)  $(DIR)$<"; \
		fi

LD_BANNER =	@if [ -t 1 ]; then \
			echo "\t\033[0;1;36m$(LD_NAME)\033[0m   $@"; \
		else \
			echo "\t$(LD_NAME)   $@"; \
		fi

%.o:		%.c
		$(CC_BANNER)
		@$(CC) $(CFLAGS) -c -o $@ $<

%.o:		%.cpp
		$(CXX_BANNER)
		@$(CC) $(CXXFLAGS) -c -o $@ $<

ifdef __DO_STATIC__
LINKAGE = -static
else
LINKAGE =
endif
