gaddr = '0x43'
iaddr = '0x27'
use-iplir = 'off'
has-xprn = 'off'
xprn-number = '1234567890123'
has-sprn = 'on'
s0 = '204'
s1 = '80'
s2 = '48'
s3 = '35'
s4 = '38'
s5 = '14'
s6 = '0'
s7 = '30'
s8 = '0'
s9 = '0'
tickets-on-kkt = 'on'
use-ppp = 'off'
local-ip = '192.168.1.57'
remote-p-ip = '192.168.1.100'
remote-s-ip = '192.168.1.100'
use-p-ip = 'on'
net-mask = '255.255.255.0'
gateway = '192.168.1.100'
tcp-cbt = 'on'
ppp-tty = '0'
ppp-speed = '1200'
ppp-init = 'ATZ'
ppp-phone = '608'
ppp-tone-dial = 'off'
ppp-auth = '1'
ppp-login = 'test'
ppp-passwd = 'test'
ppp-crtscts = 'on'
bank-system = 'on'
bank-pos-port = '0'
bank-proc-ip = '192.168.1.57'
ext-pos = 'off'
kkt = 'on'
fiscal_mode = 'off'
fdo-iface = '0'
fdo-ip = '95.128.177.216'
fdo-port = '7777'
fdo-poll-period = '60'
kkt-ip = '192.168.1.33'
kkt-netmask = '255.255.255.0'
kkt-gw = '192.168.1.100'
gprs-apn = 'internet.beeline.ru'
gprs-user = 'beeline'
gprs-passwd = 'beeline'
tax-system = '0'
kkt-log-level = '0'
kkt-log-stream = '7'
tz-offs = '0'
kkt-base-timeout = '100'
kkt-brightness = '2'
kkt-apc = 'off'
kkt-print-cheque = 'on'
kkt-print-shift-open = 'on'
kkt-print-shift-close = 'on'
kkt-print-reg = 'on'
kkt-print-rereg = 'on'
kkt-print-fs-close = 'on'
kkt-print-calc-state = 'on'
kkt-print-correction-cheque = 'on'
blank-time = '0'
color-scheme = '0'
screen-mode = '0'
screen-hints = 'on'
simple-calc = 'off'
keyboard-rate = '30'
keyboard-delay = '250'
keyboard-beeps = 'off'
